name: Make ota

on:
  workflow_dispatch:
    inputs:
      oldurl:
        description: 'using system url'
        required: true
        default: ''
      newurl:
        description: 'new system url'
        required: true
        default: ''
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:

    - name: get new rom
      run: |
        wget ${{github.event.inputs.newurl}} -O ~/new.zip
      

    - name: get old rom
      run: |
        wget ${{github.event.inputs.oldurl}} -O ~/old.zip
        ls ~/
    - name: Extract rom
      run: |
        mkdir ~/new ~/old
        unzip ~/new.zip 
        unzip ~/old.zip 
        ls
    - name: Extract payload.bin
      run: |
        wget https://github.com/ssut/payload-dumper-go/releases/download/1.2.2/payload-dumper-go_1.2.2_linux_amd64.tar.gz 
        tar zxvf payload-dumper-go_1.2.2_linux_amd64.tar.gz -o payload-dumper-go
        chmod 755 payload-dumper-go
        mkdir ~/oout ~/nout ~/out 
        ./payload-dumper-go -o ~/nout ~/new/payload.bin
        ./payload-dumper-go -o ~/oout ~/old/payload.bin
        
    - name: patch
      run: |
        a=$(ls ~/nout)
        for i in $a; do
            xdelta3 -ves ~/oout/$i ~/nout/$i ~/out/$i.xd
        done

    - name: comp
      run: |
       tar zcvf ~/out ~/xd.tgz
       ls -a ~
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: out
        path: ~/xd.tgz
