name: Make twrp-12.1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Remove Useless Package
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean
    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 1024
        swap-size-mb: 10240
        remove-dotnet: 'true'
        temp-reserve-mb: 1024
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Check Out
      uses: actions/checkout@main

    - name: get new rom
      run: |
        wget newurl -o ~/new.zip
      i

    - name: get old rom
      run: |
        wget oldurl -o ~/old.zip

    - name: Extract rom
      run: |
        unzip new
        unzip old

    - name: Extract payload.bin
      run: |
        wget https://github.com/ssut/payload-dumper-go/releases/download/1.2.2/payload-dumper-go_1.2.2_linux_amd64.tar.gz -o ~/payload-dumper.tar.gz
        tar -zxvf ~/payload-dumper.tar.gz
        ~/payload-dumper 
    - name: Repopick Patches
      run: |
        
    - name: Clone Device Tree
      run: |
        
    - name: Building
      run: |
       ls -a ~
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: rubens_twrp-12.1
        path: ~/out
