name: Make ota

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:

    - name: get new rom
      run: |
      #  wget newurl -o ~/new.zip
      

    - name: get old rom
      run: |
       # wget oldurl -o ~/old.zip

    - name: Extract rom
      run: |
       # unzip new
       # unzip old

    - name: Extract payload.bin
      run: |
        wget https://github.com/ssut/payload-dumper-go/releases/download/1.2.2/payload-dumper-go_1.2.2_linux_amd64.tar.gz -o ~/payload-dumper.tar.gz
        tar -zxvf ~/payload-dumper.tar.gz
        chmod 755 payload-dumper CT
        ~/payload-dumper 
    - name: Repopick Patches
      run: |
        
    - name: Clone Device Tree
      run: |
        
    - name: Building
      run: |
       ls -a ~
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: rubens_twrp-12.1
        path: ~/out
